### ISSUE TITLE
Question: panic d.nx != 0 calling crypto/sha1

### ISSUE THREAD

**Issue by kpacha** [catalinc/hashcash#1]
First of all, thanks for this package. We've been using it in our project since late 2018 and it works like a charm.

Today we found a weird error in our logs, this is the relevant part of the stack trace:

```
2020/04/03 07:36:03 http: panic serving 127.0.0.1:44411: d.nx != 0
goroutine 44 [running]:
net/http.(*conn).serve.func1(0xc00046c5a0)
	/usr/local/go/src/net/http/server.go:1769 +0x139
panic(0x9457a0, 0xae9990)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
crypto/sha1.(*digest).checkSum(0xc000189898, 0x0, 0x0, 0x68d90fb00000000)
	/usr/local/go/src/crypto/sha1/sha1.go:177 +0x1ce
crypto/sha1.(*digest).Sum(0xc0000f6230, 0x0, 0x0, 0x0, 0x94, 0x0, 0x0)
	/usr/local/go/src/crypto/sha1/sha1.go:156 +0x69
github.com/catalinc/hashcash.(*Hash).checkZeros(0xc00027e1c0, 0xc000356820, 0x94, 0x1)
	/go/pkg/mod/github.com/catalinc/hashcash@v0.0.0-20161205220751-e6bc29ff4de9/hashcash.go:89 +0xd0
github.com/catalinc/hashcash.(*Hash).Check(0xc00027e1c0, 0xc000356820, 0x94, 0x0)
	/go/pkg/mod/github.com/catalinc/hashcash@v0.0.0-20161205220751-e6bc29ff4de9/hashcash.go:66 +0x68
main.validate(0xc000110b80, 0xc0001cf5c0, 0x1)
	/tmp/staging/srv/service.go:108 +0x9c
```

It's the first time we've seen it and it happened just two consecutive times. Are you familiar with this?

**Comment by catalinc** [comment]
@kpacha thanks. No, I'm not familiar with the issue but it may be related to https://github.com/golang/go/issues/29543
